### ISSUE TITLE
Early kernel panic on Asus vivobook x510unr (solved) Use layout-13 for working HDMI audio instead of CodecCommander and Unable to control mic gain

### ISSUE THREAD

**Issue by vasishath** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.5-Hackintosh#8] opened 2020-04-19 09:23 UTC
I have the same laptop but i get this early kernel panic when using OpenCore on catalina 10.15.3.

`panic(cpu 4 caller 0xffffff80004652fa): Kernel trap at 0xffffff7f836537a0, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff7f836537a0, CR3: 0x0000000005a04000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff8014937e00, RCX: 0x00000000000a000b, RDX: 0xffffff7f8387eabf
RSP: 0xffffff8103fa3db8, RBP: 0xffffff8103fa3de0, RSI: 0xffffff7f8387eab4, RDI: 0xffffff7f8387ea8d
R8: 0x0000000000000001, R9: 0x000000000000000b, R10: 0x000000807fffefff, R11: 0x0000000000000010
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff80148efec0, R15: 0xffffff80148efec0
RFL: 0x0000000000210246, RIP: 0xffffff7f836537a0, CS: 0x0000000000000008, SS: 0x0000000000000000
Fault CR2: 0xffffff7f836537a0, Error code: 0x0000000000000010, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffff8103fa3810 : 0xffffff800033bb2b mach_kernel : _handle_debugger_trap + 0x47b
0xffffff8103fa3860 : 0xffffff80004734d5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff8103fa38a0 : 0xffffff8000464f4e mach_kernel : _kernel_trap + 0x4ee
0xffffff8103fa38f0 : 0xffffff80002e2a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8103fa3910 : 0xffffff800033b217 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff8103fa3a10 : 0xffffff800033b5fb mach_kernel : _panic_trap_to_debugger + 0x21b
0xffffff8103fa3a60 : 0xffffff8000ad2aa9 mach_kernel : _panic + 0x61
0xffffff8103fa3ad0 : 0xffffff80004652fa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff8103fa3c50 : 0xffffff8000464ff8 mach_kernel : _kernel_trap + 0x598
0xffffff8103fa3ca0 : 0xffffff80002e2a40 mach_kernel : _return_from_trap + 0xe0
0xffffff8103fa3cc0 : 0xffffff7f836537a0
0xffffff8103fa3de0 : 0xffffff8000a1b216 mach_kernel : _ZN9IOService14startCandidateEPS + 0xf6
0xffffff8103fa3e40 : 0xffffff8000a1adc1 mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xb21
0xffffff8103fa3ef0 : 0xffffff8000a1a10e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2ce
0xffffff8103fa3f50 : 0xffffff8000a1c8ad mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x15d
0xffffff8103fa3fa0 : 0xffffff80002e213e mach_kernel : _call_continuation + 0x2e

BSD process name corresponding to current thread: Unknown
Boot args: -v keepsyms=1

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 19.3.0: Thu Jan 9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
Kernel UUID: A8DDE75C-CD97-3C37-B35D-1070CC50D2CE
__HIB text base: 0xffffff8000100000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 1985931883`

I am using clover currently to boot macos. I have also tried resetting NVRAM multiple times but it didn't help either.

**Comment by whatnameisit** [comment] 2020-04-19 09:45
Please make sure you are using the latest commit, and if not upload your OC folder.
Alternatively, you can try the latest commit before I switched to 0.5.7 for 10.15.4: https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh/tree/71baa6e01595d1158112988506557ba33efff87a
Or you can try to update to 10.15.4 using Clover and switch to OpenCore as the other user abhidiwakar has the same system working on 10.15.4.

**Comment by vasishath** [comment] 2020-04-19 16:52
> Please make sure you are using the latest commit, and if not upload your OC folder.
> Alternatively, you can try the latest commit before I switched to 0.5.7 for 10.15.4: https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh/tree/71baa6e01595d1158112988506557ba33efff87a
> Or you can try to update to 10.15.4 using Clover and switch to OpenCore as the other user abhidiwakar has the same system working on 10.15.4.
So I decided to upgrade my installation to 10.15.4 and in preparation for that, I deleted all kexts from /L/E and just before beginning to install the update, I decided to give opencore a try and it booted just fine.

So I guess same kexts shouldn't be present in /L/E that are there in EFI.

**Comment by whatnameisit** [comment] 2020-04-19 22:15
> So I decided to upgrade my installation to 10.15.4 and in preparation for that, I deleted all kexts from /L/E and just before beginning to install the update

If you use Clover or OpenCore to load kexts, you shoud not have the same kexts inside /L/E or /S/L/E because the same kexts will be loaded twice resulting in unexpected behaviors. Clover has the option to inject kexts if no SMC kext(VirtualSMC or FakeSMC) is found "detected", but there is no such option in OpenCore as the devs expect no signed kexts can be loaded from cache in the near future.
Until then, you need to load one kext from /L/E, however: CodecCommander for internal mic. It cannot function in Vivobooks if not loaded from cached kernel.
I will close the issue as solved, but feel free to open it if anything I said does not seem to be your case.

**Comment by vasishath** [comment] 2020-04-25 14:55
In latest AppleALC release, I just checked that with layout-id=13, mic is working without codeccommander. That id is exclusive for some Asus laptops. Though the series is S4xx

**Comment by whatnameisit** [comment] 2020-04-26 00:56
@vasishath yes, the mic worked with layout-id 13 from since 1.4.3. I have tried that. But HDMI audio doesn't work with it which is why I kept 3 (Internal and HDMI output) and CodecCommander (Mic).

**Comment by vasishath** [comment] 2020-04-26 02:27
> @vasishath yes, the mic worked with layout-id 13 (Internal input aka mic and output) since 1.4.3. I have tried that. But HDMI audio doesn't work with it which is why I kept 3 (Internal and HDMI output) and CodecCommander (Mic).

This calls for a separate layout for our vivobook. I will try to add support for it.

**Comment by whatnameisit** [comment] 2020-04-26 03:43
It'd be great If you could do it. Perhaps you should contact cowpod since he is the one who incorporated mic support into AppleALC for his machine.

**Comment by vasishath** [comment] 2020-04-30 14:22
> It'd be great If you could do it. Perhaps you should contact cowpod since he is the one who incorporated mic support into AppleALC for his machine.

I checked with layout id 3, and found that hdmi doesn't work for me on that either. Also I found that layout 13 has nothing different than added wake config data for mic. If that is added to layout 3, mic starts working.

If somehow one still wants to use codeccommander, then he can load it from EFI and then use hda-verb binary to manually send the commands to wake the mic up. That also works.

**Comment by whatnameisit** [comment] 2020-04-30 21:16
Layout-3 and -13 are different such that some code needs to be added as you said and some replaced. Use a comparison tool to find out.
If you want, you can make the necessary commits on the usage of hda-verb binary and the corresponding pull request.

**Comment by vasishath** [comment] 2020-05-01 02:03
> Layout-3 and -13 are different such that some code needs to be added as you said and some replaced. Use a comparison tool to find out.
> If you want, you can make the necessary commits on the usage of hda-verb binary and the corresponding pull request.

Yes I have checked the diff and found mic gain data as the only difference. And yes I will create a pull request but can u just confirm if hdmi audio really works with layout 3 ? Because for me the audio output tab shows no output devices available when I switch to hdmi and the panel volume icon grays out.

**Comment by whatnameisit** [comment] 2020-05-01 02:25
Unable to control HDMI volume in OS is macOS HDMI thing. I haven't tested HDMI audio since 10.14.6, but it should work and the volume, too, by pressing control buttons on the monitor.

**Comment by vasishath** [comment] 2020-05-01 15:48
> Unable to control HDMI volume in OS is macOS HDMI thing. I haven't tested HDMI audio since 10.14.6, but it should work and the volume, too, by pressing control buttons on the monitor. I don't know about no audio device detected though.

I can confirm that HDMI audio works on layout 13 as well. I initially thought unable to control volume means no HDMI audio. So I guess it's way easier to switch to layout 13 as going through codeccommander for the same thing makes things complex for an average user. Now the only thing that bothers is mic gain can't be controlled.

**Comment by whatnameisit** [comment] 2020-05-01 22:18
Please post a video clip to show HDMI audio works with 13. It'd be great if you could prove you have not loaded CodecCommander (and disabled SSDT-CC.aml) by recording the clip with terminal "kextstat | grep CodecCommander"
And next time, let's make separate issues for separate things :)

**Comment by whatnameisit** [comment] 2020-06-09 22:14
@vasishath I noticed you have made a PR in AppleALC concerning this issue and it was merged. I assume our problems are solved, although you have failed to prove it.

**Closed by whatnameisit** 2020-06-09 22:14 UTC
